name: Build and create a release when tag is pushed

# Only deploy when a new tag is pushed
on:
    push:
        tags:
          - "v*.*-alpha"
          - "v*.*.*"
          
# Must match the project() name in CMakeLists.txt
env:
    APP_NAME: PicoSystem_InfoNes

# Allow this workflow to write back to the repository
permissions:
    contents: write
    
# Build binary and send to releases
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        name: Build and deploy
        steps:
          
          - name: Install dependencies
            run: |
                 sudo apt update && \
                 sudo apt install -y git python3 && \
                 sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
                 
          - name: Check out this repository
            uses: actions/checkout@v3

          - name: Print Working directory
            run: echo $HOME && pwd && ls -la

          - name: Install Pico SDk
            run: |
                 cd $HOME && \
                 git clone https://github.com/raspberrypi/pico-sdk.git --branch master && \
                 cd pico-sdk/ && \
                 git submodule update --init

          - name: Build the project
            run: |
                 export PICO_SDK_PATH=$HOME/pico-sdk && \
                 mkdir build && cd build && \
                 cmake .. && \
                 make

          - name: download latest release of PicoSystemInfoNesLoader.zip
            run: |
                 ASSET_URL=$(curl -s "https://api.github.com/repos/fhoedemakers/PicoSystemInfoNesLoader/releases/latest" | jq -r '.assets[0].browser_download_url')
                 wget -q "$ASSET_URL" -O PicoSystemInfoNesLoader.zip

          - name: Create release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: |
                       build/${{ env.APP_NAME }}.uf2
                       PicoSystemInfoNesLoader.zip           
                body_path: CHANGELOG.md
          
         